# -*- coding: utf-8 -*-
"""pociones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjVNmf2uc72d0RwqV6RAj8vIQSrzz8x7
"""

x = 2
y = 2
res =x+y
y = 6
res = x+y



import random

efectos = [
    "Te hace volar( ᴗ͈ˬᴗ͈)ഒ",
    "Te vuelve invisible(,; ⩌ ;,)",
    "Te permite hablar con animales⚞^. .^⚟",
    "Te da suerte ilimitadaദ്ദി(˵ •̀ ᴗ - ˵ ) ✧",
    "Te hace cambiar de color(๑>؂•̀๑)",
    "Te hace hablar con las flores(*ᴗ͈ˬᴗ͈)ꕤ*.ﾟ"
    ]

ingredientes = [ #ingredientes tiernos nanananana
    "polvo de luna",
    "trocitos de estrellas",
    "mezcla de trévoles de cuatro hojas",
    "cataratas de arcoiris",
    "bocados de nube",
    "semillas de felicidad֒",
    "chispas de corales"
]

mezcla = []
for i in (0,1):
  print(ingredientes)
  ing = input("¿Qué deseas añadir? ")
  if ing.lower() in ingredientes:
    ingredientes.remove(ing)
  else:
    pass

  mezcla.append(ing)


result = random.choice(efectos)
print("Tu mezcla tiene: ", mezcla)
print("Tu nueva poción:", result)

